FROM golang:1.17

WORKDIR /work
COPY . .
RUN go build -o qvs-workshop-app main.go

# ENV DISABLE_DB
# ENV REDIS_PASS
# ENV DISABLE_REDIS

# ARG PORT
# ARG DB_HOST
# ARG DB_USER
# ARG DB_PASS
# ARG REDIS_HOST
# ARG REDIS_PORT
# ARG REDIS_PASS

# ENV PORT=$PORT
# ENV DB_HOST=$DB_HOST
# ENV DB_USER=$DB_USER
# ENV DB_PASS=$DB_PASS
# ENV REDIS_HOST=$REDIS_HOST
# ENV REDIS_PORT=$REDIS_PORT
# ENV REDIS_PASS=$REDIS_PASS

CMD ["./qvs-workshop-app"]
